version: 0.2
phases:
  install:
    runtime-versions:
       python: 3.9
    commands:
      - pip install cfn-lint
  pre_build:
    commands:
      - echo "Validating SAM template"
      - |
        echo "Validating template file template.yml"
        cfn-lint -t template.yml
  build:
    commands:
      - sam build
      - sam package
        --template-file template.yml
        --output-template-file packaged-template.yml
        --s3-bucket $TEMPLATE_BUCKET

artifacts:
  files:
    - packaged-template.yml
    - config-*.json